# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1444036952);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140716183446");
user_pref("browser.slowStartup.averageTime", 6178);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20140716183446");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"webrtc-status-button\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"social-share-button\",\"action-button--jid1-dwtfbkqjb3siqpjetpack-iadblocklite\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"action-button--jid1-dwtfbkqjb3siqpjetpack-iadblocklite\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"newElementCount\":0}");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1444123232158");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1444036832158");
user_pref("datareporting.sessions.current.activeTicks", 35);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4579);
user_pref("datareporting.sessions.current.main", 250);
user_pref("datareporting.sessions.current.sessionRestored", 6256);
user_pref("datareporting.sessions.current.startTime", "1444036830342");
user_pref("datareporting.sessions.current.totalTime", 193);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"jid1-dwtFBkQjb3SIQp@jetpack\":{\"version\":\"0.2.7\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Users\\\\johnsir.BRILLIO\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\z0pfyd4d.AdBlocker\\\\extensions\\\\jid1-dwtFBkQjb3SIQp@jetpack.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"fiddlerhook@fiddler2.com\":{\"descriptor\":\"C:\\\\Program Files\\\\Fiddler2\\\\FiddlerHook\",\"mtime\":1439879214507,\"rdfTime\":1439237696000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1441184852232,\"rdfTime\":1405567032000}}},{\"name\":\"winreg-app-user\",\"addons\":{\"wcapturex@deskperience.com\":{\"descriptor\":\"C:\\\\Program Files\\\\WordWeb\\\\WCaptureMoz\",\"mtime\":1409219128000,\"rdfTime\":1367545909000}}}]");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.allowedURLs", "[\"charity.org\",\"www.gnome.org\",\"www.cancer.org\",\"www.concern.net\",\"sourceforge.net\",\"www.redcross.org\",\"www.wikipedia.org\",\"chrome.google.com\",\"stackoverflow.com\",\"mybrowseraddon.com\",\"www.worldvision.org\",\"www.latex-project.org\",\"redribbonfoundation.org\",\"www.linuxfoundation.org\",\"www.libreoffice.org\",\"addons.mozilla.org\",\"www.openoffice.org\",\"addons.opera.com\",\"www.unicef.org\",\"www.kernel.org\",\"opensource.org\",\"github.com\",\"nodejs.org\",\"nrdc.org\"]");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.customRule", "[]");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.fullLite", "Lite");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.highlight", "block");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.rid", "ss088uf6yu");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.startStop", "Enable");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.tableType", "add");
user_pref("extensions.jid1-dwtFBkQjb3SIQp@jetpack.version", "0.2.7");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/ad%20block");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20140716183446");
user_pref("gecko.mstone", "31.0");
user_pref("gfx.direct3d.last_used_feature_level_idx", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 79620);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1444036830);
user_pref("toolkit.telemetry.previousBuildID", "20140716183446");
