# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1389597618);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1389597379);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1389597498);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 8685);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1389683778418");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1389597378417");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 7154);
user_pref("datareporting.sessions.current.main", 1059);
user_pref("datareporting.sessions.current.sessionRestored", 8041);
user_pref("datareporting.sessions.current.startTime", "1389597375555");
user_pref("datareporting.sessions.current.totalTime", 274);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0.1");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"fiddlerhook@fiddler2.com\":{\"descriptor\":\"C:\\\\Program Files\\\\Fiddler2\\\\FiddlerHook\",\"mtime\":1378272812181,\"rdfTime\":1369327018000},\"{22C7F6C6-8D67-4534-92B5-529A0EC09405}\":{\"descriptor\":\"C:\\\\Program Files\\\\Trend Micro\\\\OfficeScan Client\\\\FirefoxExtension\",\"mtime\":1385350152545,\"rdfTime\":1372676618000},\"aeffagent@dynatrace.com\":{\"descriptor\":\"C:\\\\Program Files\\\\dynaTrace\\\\dynaTrace AJAX Edition 4.3\\\\client\\\\lib\\\\aeffagent@dynatrace.com\",\"mtime\":1389597246758,\"rdfTime\":1386217664000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1376892324685,\"rdfTime\":1376892324463}}},{\"name\":\"winreg-app-user\",\"addons\":{\"wcapturex@deskperience.com\":{\"descriptor\":\"C:\\\\Program Files\\\\WordWeb\\\\WCaptureMoz\",\"mtime\":1379495178886,\"rdfTime\":1367545909000},\"aeffagent@dynatrace.com\":{\"descriptor\":\"C:\\\\Program Files\\\\dynaTrace\\\\dynaTrace AJAX Edition 4.3\\\\client\\\\lib\\\\aeffagent@dynatrace.com\",\"mtime\":1389597246758,\"rdfTime\":1386217664000}}}]");
user_pref("extensions.lastAppVersion", "23.0.1");
user_pref("extensions.lastPlatformVersion", "23.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.enabled", false);
user_pref("gecko.buildID", "20130814063812");
user_pref("gecko.mstone", "23.0.1");
user_pref("gfx.direct3d.last_used_feature_level_idx", 1);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 79620);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1389597376);
user_pref("toolkit.telemetry.previousBuildID", "20130814063812");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1392189391);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
