# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1393955591);
user_pref("app.update.lastUpdateTime.background-update-timer", 1393955436);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1393955197);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1393955316);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.buildID", "20130511120803");
user_pref("browser.startup.homepage_override.mstone", "21.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1394041596401");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1393955196401");
user_pref("datareporting.sessions.current.activeTicks", 11);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 6147);
user_pref("datareporting.sessions.current.main", 62);
user_pref("datareporting.sessions.current.sessionRestored", 6175);
user_pref("datareporting.sessions.current.startTime", "1393955470711");
user_pref("datareporting.sessions.current.totalTime", 121);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1393955195741,\"a\":12,\"t\":271,\"c\":true,\"m\":46,\"fp\":1512,\"sr\":1943}");
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("dtagent.logdir", "C:\\Users\\QAAutomationSVC\\AppData\\LocalLow\\dynaTrace\\browser\\");
user_pref("extensions.adblockplus.currentVersion", "2.5.1");
user_pref("extensions.adblockplus.notificationdata", "{\"shown\":[]}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"version\":\"2.5.1\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Users\\\\QAAutomationSVC\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\_dt_profile_no_ads\\\\extensions\\\\{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "dtffagent%40dynatrace.com:5.5.0.5232,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:21.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1390329093800,\"rdfTime\":1368303951000}}},{\"name\":\"winreg-app-user\",\"addons\":{\"dtffagent@dynatrace.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\dynaTrace\\\\dynaTrace Agent 5.5.0\\\\agent\\\\lib\\\\dtffagent@dynatrace.com\",\"mtime\":1389908742244,\"rdfTime\":1372987554000}}},{\"name\":\"app-profile\",\"addons\":{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"C:\\\\Users\\\\QAAutomationSVC\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\_dt_profile_no_ads\\\\extensions\\\\{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"mtime\":1393955234725}}}]");
user_pref("extensions.lastAppVersion", "21.0");
user_pref("extensions.lastPlatformVersion", "21.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130511120803");
user_pref("gecko.mstone", "21.0");
user_pref("idle.lastDailyNotification", 1393955421);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1393955421);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1393955421);
user_pref("toolkit.startup.last_success", 1393955470);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1396547201);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
